name: pancake

include:
  - path: service-api.yml

services:
  nginx:
    image: nginx:1-alpine-slim
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80