name: pancake

include:
  - path: compose-service-api.yml

services:
  nginx:
    image: nginx:1-alpine-slim
    depends_on:
      ssl:
        condition: service_completed_successfully
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ssl_certificates:/etc/nginx/ssl:ro
    ports:
      - 8080:80
      - 8443:443

  ssl:
    image: certbot/certbot:latest
    volumes:
      - ssl_certificates:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    command: >
      certonly
        --standalone
        --domain pancake.viiviii.xyz
        --disable-hook-validation --deploy-hook 
          'cd /etc/letsencrypt && ln -s live/$$RENEWED_DOMAINS/fullchain.pem cert.pem && ln -s live/$$RENEWED_DOMAINS/privkey.pem key.pem'
        --email viiiix.viiviii@gmail.com --agree-tos --no-eff-email
        --keep-until-expiring

volumes:
  ssl_certificates:
