spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  lifecycle.timeout-per-shutdown-phase: "30s"
server:
  shutdown: graceful

---

spring:
  config.activate.on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:tcp://localhost/~/pancake}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.format_sql: true
logging.level:
  org.hibernate.SQL: debug # SQL logger 통해 출력
