spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    hibernate:
      ddl-auto: validate

server:
  shutdown: graceful

---

spring:
  config.activate.on-profile: local
  jpa:
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.SQL: debug # SQL logger 통해 출력
